version: "3"
services:
  mongodb:
    image: mongo:7.0.1
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - m7011e:/data/db

  webservice:
    #image: ${REPOSITORY}:latest
    image: webservice # for running local build aka "make build"
    container_name: webservice
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - compose/.env
    restart: unless-stopped
    ports:
      - "5000:5000"

volumes:
  m7011e:
