version: "3"
services:
  mongodb:
    image: mongo:7.0.1
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - m7011e:/data/db

volumes:
  m7011e: